ALTER TABLE public.sis_usuario 
    ALTER COLUMN senha_usuario TYPE TEXT;

ALTER TABLE public.sis_usuario
    ALTER COLUMN id_usuario_exclusao DROP NOT NULL,
    ALTER COLUMN data_exclusao DROP NOT NULL,
    ALTER COLUMN id_usuario_alteracao DROP NOT NULL,
    ALTER COLUMN data_alteracao DROP NOT NULL,
    ALTER COLUMN id_usuario_inclusao DROP NOT NULL;

ALTER TABLE public.sis_usuario 
    ALTER COLUMN id_usuario ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE public.sis_usuario
    ALTER COLUMN uuid_usuario SET DEFAULT gen_random_uuid();

ALTER TABLE public.sis_usuario
    ALTER COLUMN data_inclusao SET DEFAULT NOW();

ALTER TABLE public.sis_usuario
    RENAME COLUMN cpf_cnpj TO cnpj_cpf;